-- ============================================================================
-- Navkar Stationary — Supabase (Postgres) Schema
-- ============================================================================
-- HOW TO USE:
-- 1. Go to your Supabase project → SQL Editor → New Query
-- 2. Paste this entire file and click "Run"
-- 3. This creates all 6 tables the app needs, replacing the old MongoDB
--    collections (queries, xerox_requests, products, orders, trash,
--    announcements) one-for-one.
-- ============================================================================

-- 1. QUERIES (homepage "Submit a Query" form)
create table if not exists public.queries (
    id              bigint generated by default as identity primary key,
    name            text,
    whatsapp_number text,
    department      text,
    course          text,
    semester        text,
    subject         text,
    status          text default 'Pending',
    admin_message   text default '',
    date            text,
    created_at      timestamptz default now()
);

-- 2. XEROX / PRINT REQUESTS
create table if not exists public.xerox_requests (
    id                  bigint generated by default as identity primary key,
    name                text,
    whatsapp_number     text,
    department          text,
    course              text,
    semester            text,
    original_filename   text,
    stored_filename     text,
    copies              text,
    instructions        text,
    status              text default 'Pending',
    date                text,
    created_at          timestamptz default now()
);

-- 3. PRODUCTS (stock / shop items)
create table if not exists public.products (
    id          bigint generated by default as identity primary key,
    name        text,
    price       numeric default 0,
    photo       text,
    category    text default 'Uncategorized',
    date        text,
    created_at  timestamptz default now()
);

-- 4. ORDERS (submitted shopping carts)
create table if not exists public.orders (
    id              bigint generated by default as identity primary key,
    name            text,
    whatsapp_number text,
    line_items      jsonb default '[]',
    total           numeric default 0,
    comment         text default '',
    status          text default 'Pending',
    date            text,
    created_at      timestamptz default now()
);

-- 7. REVIEWS (customer feedback -> shown as "Our Happy Customers" on homepage)
create table if not exists public.reviews (
    id              bigint generated by default as identity primary key,
    name            text,
    whatsapp_number text,
    review_text     text,
    rating          int default 5,
    status          text default 'Pending', -- Pending | Approved | Deleted
    date            text,
    created_at      timestamptz default now()
);

-- 5. TRASH (soft-deleted orders)
create table if not exists public.trash (
    id                  bigint generated by default as identity primary key,
    original_order_id   bigint,
    name                text,
    whatsapp_number     text,
    line_items          jsonb default '[]',
    total               numeric default 0,
    status              text,
    date                text,
    deleted_date        text,
    created_at          timestamptz default now()
);

-- 6. ANNOUNCEMENTS (circular homepage bubbles)
create table if not exists public.announcements (
    id          bigint generated by default as identity primary key,
    title       text,
    message     text,
    icon        text,
    color       text,
    date        text,
    created_at  timestamptz default now()
);

-- 8. REPORT STUDENTS (report-generation pipeline)
-- ----------------------------------------------------------------------------
-- Every time a Query or Xerox form is submitted, the app ALSO copies just the
-- report-relevant fields (name, whatsapp_number, department, course,
-- semester) into this separate table. It is purely an additive side-copy -
-- the original `queries` / `xerox_requests` rows and workflow are never
-- touched, read, or altered by report generation.
--
-- De-duplication: `whatsapp_number` is UNIQUE. If a form is submitted with a
-- WhatsApp number that already exists here, that row is UPDATED in place
-- (upsert) with the latest name/department/course/semester instead of
-- creating a second row for the same student. Different WhatsApp numbers
-- always create a new, unique row.
create table if not exists public.report_students (
    id              bigint generated by default as identity primary key,
    name            text,
    whatsapp_number text unique,
    department      text,
    course          text,
    semester        text,
    updated_at      timestamptz default now()
);

-- ============================================================================
-- Row Level Security
-- ----------------------------------------------------------------------------
-- The Flask backend talks to Supabase using the SERVICE ROLE key (kept secret
-- in your .env file, never sent to the browser). The service role key always
-- bypasses Row Level Security, so the app will keep working even with RLS on.
-- We enable RLS with no public policies here as a safety net, in case the
-- anon/public key is ever used accidentally.
-- ============================================================================
alter table public.queries enable row level security;
alter table public.xerox_requests enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.trash enable row level security;
alter table public.announcements enable row level security;
alter table public.reviews enable row level security;
alter table public.report_students enable row level security;

-- ============================================================================
-- MIGRATION (run this if you already created the tables above previously)
-- ----------------------------------------------------------------------------
-- Safe to run any time — each statement only adds a column/table if missing.
-- ============================================================================
alter table public.xerox_requests add column if not exists department text;
alter table public.xerox_requests add column if not exists semester text;
alter table public.products add column if not exists category text default 'Uncategorized';
alter table public.orders add column if not exists comment text default '';

-- Added for: extra "Course" field on Query & Xerox forms + report generation
alter table public.queries add column if not exists course text;
alter table public.xerox_requests add column if not exists course text;

-- Added for: Admin > Reports (Excel report generation) pipeline table.
-- Safe to run even if the table already exists from the CREATE TABLE above.
create table if not exists public.report_students (
    id              bigint generated by default as identity primary key,
    name            text,
    whatsapp_number text unique,
    department      text,
    course          text,
    semester        text,
    updated_at      timestamptz default now()
);
alter table public.report_students enable row level security;
-- If report_students already existed WITHOUT a unique constraint on
-- whatsapp_number (e.g. created by an older version of this file), this adds
-- it so WhatsApp-number de-duplication (upsert) works correctly.
do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'report_students_whatsapp_number_key'
    ) then
        alter table public.report_students
            add constraint report_students_whatsapp_number_key unique (whatsapp_number);
    end if;
end $$;
