-- ============================================================================
-- Navkar Stationary — Supabase (Postgres) Schema
-- ============================================================================
-- HOW TO USE:
-- 1. Go to your Supabase project → SQL Editor → New Query
-- 2. Paste this entire file and click "Run"
-- 3. This creates all 6 tables the app needs, replacing the old MongoDB
--    collections (queries, xerox_requests, products, orders, trash,
--    announcements) one-for-one.
-- ============================================================================

-- 1. QUERIES (homepage "Submit a Query" form)
create table if not exists public.queries (
    id              bigint generated by default as identity primary key,
    name            text,
    whatsapp_number text,
    department      text,
    semester        text,
    subject         text,
    status          text default 'Pending',
    admin_message   text default '',
    date            text,
    created_at      timestamptz default now()
);

-- 2. XEROX / PRINT REQUESTS
create table if not exists public.xerox_requests (
    id                  bigint generated by default as identity primary key,
    name                text,
    whatsapp_number     text,
    original_filename   text,
    stored_filename     text,
    copies              text,
    instructions        text,
    status              text default 'Pending',
    date                text,
    created_at          timestamptz default now()
);

-- 3. PRODUCTS (stock / shop items)
create table if not exists public.products (
    id          bigint generated by default as identity primary key,
    name        text,
    price       numeric default 0,
    photo       text,
    date        text,
    created_at  timestamptz default now()
);

-- 4. ORDERS (submitted shopping carts)
create table if not exists public.orders (
    id              bigint generated by default as identity primary key,
    name            text,
    whatsapp_number text,
    line_items      jsonb default '[]',
    total           numeric default 0,
    status          text default 'Pending',
    date            text,
    created_at      timestamptz default now()
);

-- 5. TRASH (soft-deleted orders)
create table if not exists public.trash (
    id                  bigint generated by default as identity primary key,
    original_order_id   bigint,
    name                text,
    whatsapp_number     text,
    line_items          jsonb default '[]',
    total               numeric default 0,
    status              text,
    date                text,
    deleted_date        text,
    created_at          timestamptz default now()
);

-- 6. ANNOUNCEMENTS (circular homepage bubbles)
create table if not exists public.announcements (
    id          bigint generated by default as identity primary key,
    title       text,
    message     text,
    icon        text,
    color       text,
    date        text,
    created_at  timestamptz default now()
);

-- ============================================================================
-- Row Level Security
-- ----------------------------------------------------------------------------
-- The Flask backend talks to Supabase using the SERVICE ROLE key (kept secret
-- in your .env file, never sent to the browser). The service role key always
-- bypasses Row Level Security, so the app will keep working even with RLS on.
-- We enable RLS with no public policies here as a safety net, in case the
-- anon/public key is ever used accidentally.
-- ============================================================================
alter table public.queries enable row level security;
alter table public.xerox_requests enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.trash enable row level security;
alter table public.announcements enable row level security;
